[build-dependencies]
tauri-plugin = { path = "../../../../crates/tauri-plugin", features = [
	"build",
] }

[dependencies]
log = { version = "0.4" }
serde = { version = "1" }
tauri = { path = "../../../../crates/tauri" }
thiserror = { version = "2" }

[lib]
path = "Source/lib.rs"

[package]
edition = "2021"
links = "tauri-plugin-sample"
name = "tauri-plugin-sample"
version = "0.1.0"
