[dependencies]
aes-gcm = { version = "0.10", optional = true }
brotli = { version = "7", optional = true, default-features = false, features = [
	"std",
] }
cargo_metadata = { version = "0.19", optional = true }
ctor = { version = "0.3" }
dunce = "1"
getrandom = { version = "0.3", optional = true, features = ["std"] }
glob = { version = "0.3" }
html5ever = { version = "0.29" }
http = "1"
infer = "0.19"
json-patch = "3.0"
json5 = { version = "0.4", optional = true }
kuchiki = { package = "kuchikiki", version = "0.8" }
log = "0.4.25"
memchr = "2"
phf = { version = "0.11", features = ["macros"] }
proc-macro2 = { version = "1", optional = true }
quote = { version = "1", optional = true }
regex = { version = "1" }
schemars = { version = "0.8.21", features = ["url", "uuid1"], optional = true }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde-untagged = "0.1"
serde_json = { version = "1" }
serde_with = "3"
serialize-to-javascript = { version = "=0.1.1", optional = true }
thiserror = { version = "2" }
toml = { version = "0.8", features = ["parse"] }
url = { version = "2", features = ["serde"] }
urlpattern = { version = "0.3" }
uuid = { version = "1", features = ["serde"] }
walkdir = { version = "2", optional = true }

[dev-dependencies]
getrandom = { version = "0.3", features = ["std"] }
serial_test = "3"

[features]
build = ["proc-macro2", "quote", "cargo_metadata", "schema", "swift-rs"]
compression = ["brotli"]
config-json5 = ["json5"]
config-toml = []
isolation = ["aes-gcm", "getrandom", "serialize-to-javascript"]
process-relaunch-dangerous-allow-symlink-macos = []
resources = ["walkdir"]
schema = ["schemars"]

[lib]
path = "Source/lib.rs"

[package]
description = "Utilities for Tauri"
exclude = ["CHANGELOG.md", "/target"]
name = "tauri-utils"
readme = "README.md"
version = "2.1.1"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true

[package.rust-version]
workspace = true

[target]

[target.'cfg(target_os = "macos")']

[target.'cfg(target_os = "macos")'.dependencies]
swift-rs = { version = "1", optional = true, features = ["build"] }
