[[bin]]
name = "tauri-schema-generator"
path = "Source/main.rs"

[build-dependencies]
schemars = { version = "0.8.21", features = ["url", "preserve_order"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-utils = { features = ["schema"], path = "../tauri-utils" }
url = { version = "2", features = ["serde"] }

[package]
edition = "2024"
name = "tauri-schema-generator"
publish = false
version = "0.0.0"
