[dependencies]
anyhow = "1"
apple-codesign = { version = "0.29", default-features = false }
chrono = "0.4"
dirs = "6"
log = { version = "0.4.27", features = ["kv"] }
once-cell-regex = "0.2"
os_pipe = "1"
p12 = "0.6"
plist = "1"
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
x509-certificate = "0.24"

[lib]
path = "Source/lib.rs"

[package]
authors = ["Tauri Programme within The Commons Conservancy"]
description = "Code signing utilities for macOS and iOS apps"
edition = "2024"
keywords = ["codesign", "signing", "macos", "ios", "tauri"]
license = "Apache-2.0 OR MIT"
name = "tauri-macos-sign"
repository = "https://github.com/tauri-apps/tauri"
rust-version = "1.77.2"
version = "2.1.0"
