[dependencies]
anyhow = "1"
axum = { version = "0.8", default-features = false }
console_error_panic_hook = { version = "0.1" }
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
tower-service = "0.3"
worker = { version = "0.5", features = ['http', 'axum'] }
worker-macros = { version = "0.5", features = ['http'] }

[lib]
crate-type = ["cdylib"]
path = "Source/lib.rs"

[lints]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(wasm_bindgen_unstable_test_coverage)',
] }

[package]
edition = "2024"
name = "tauri-schema-worker"
publish = false
version = "0.0.0"
