name: NPM

concurrency:
    group: NPM-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.1.2

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Publish ./examples/api
              continue-on-error: true
              working-directory: ./examples/api
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./examples/file-associations
              continue-on-error: true
              working-directory: ./examples/file-associations
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./examples/resources
              continue-on-error: true
              working-directory: ./examples/resources
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./examples/web
              continue-on-error: true
              working-directory: ./examples/web
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish .
              continue-on-error: true
              working-directory: .
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/api
              continue-on-error: true
              working-directory: ./tooling/api
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/darwin-arm64
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/darwin-arm64
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/darwin-x64
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/darwin-x64
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/linux-arm-gnueabihf
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/linux-arm-gnueabihf
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/linux-arm64-gnu
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/linux-arm64-gnu
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/linux-arm64-musl
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/linux-arm64-musl
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/linux-x64-gnu
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/linux-x64-gnu
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/linux-x64-musl
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/linux-x64-musl
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/win32-arm64-msvc
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/win32-arm64-msvc
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/win32-ia32-msvc
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/win32-ia32-msvc
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node/npm/win32-x64-msvc
              continue-on-error: true
              working-directory: ./tooling/cli/node/npm/win32-x64-msvc
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/node
              continue-on-error: true
              working-directory: ./tooling/cli/node
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/templates/plugin/__example-api/tauri-app
              continue-on-error: true
              working-directory: ./tooling/cli/templates/plugin/__example-api/tauri-app
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/templates/plugin/__example-basic/vanilla
              continue-on-error: true
              working-directory: ./tooling/cli/templates/plugin/__example-basic/vanilla
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tooling/cli/templates/plugin
              continue-on-error: true
              working-directory: ./tooling/cli/templates/plugin
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
